/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ezcanteen1;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
     Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
    String user = "abcdef";
    String pass = "abcdef";
    public LoginGUI() {
        initComponents();
        this.setSize(691,346);
        this.setLocation(350,150);
        Color c = new Color(40,40,40);
        con=Concls.dbconnect();
        this.getContentPane().setBackground(c);
        
    }
  public void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_user = new javax.swing.JTextField();
        t_pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reset_pass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(40, 40, 40));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(154, 11, 0, 0);

        login.setBackground(new java.awt.Color(40, 40, 40));
        login.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        login.setForeground(new java.awt.Color(240, 240, 240));
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/login1.jpg"))); // NOI18N
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(280, 240, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/usename.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 130, 120, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/password (1).jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 190, 120, 30);

        t_user.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(t_user);
        t_user.setBounds(260, 130, 200, 32);

        t_pass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        t_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_passKeyPressed(evt);
            }
        });
        getContentPane().add(t_pass);
        t_pass.setBounds(260, 190, 200, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/min.jpg"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(630, 10, 20, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/close.jpg"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(660, 10, 20, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/login.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 10, 490, 80);

        reset_pass.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        reset_pass.setForeground(new java.awt.Color(240, 240, 240));
        reset_pass.setText("Reset Password");
        reset_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_passMouseClicked(evt);
            }
        });
        getContentPane().add(reset_pass);
        reset_pass.setBounds(520, 300, 130, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
             if(t_user.getText().equals("")||t_pass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the Username and Password .","User Login",2);
        }
        else
        {
                 try {
                     String sql="Select * from accdetails where username=? and password=?";
                     ps=con.prepareStatement(sql);
                     ps.setString(1,t_user.getText() );
                     ps.setString(2,t_pass.getText() );
                     
                     
                     rs=ps.executeQuery();
                     
                     if(rs.next())
                         //  if(t_user.getText().equals(user)&&t_pass.getText().equals(pass))
                     {
                         JOptionPane.showMessageDialog(null,"Login Successful .","User Login",1);
                         
                         MainGUI m = new MainGUI();
                         m.setVisible(true);
                         ps.close();
                         rs.close();
                         close();
                         
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(null,"Invalid Username or Password .","User Login",0);
                         t_user.setText("");
                         t_pass.setText("");
                     }   } catch (SQLException ex) {
                     Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                 }
                       finally{
             try
             {
                 rs.close();
                 ps.close();
                 con.close();
             }
             catch(Exception e){}
             
         }
        }
    }//GEN-LAST:event_loginMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void reset_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_passMouseClicked
        // TODO add your handling code here:
       
        ResetPassGUI r = new ResetPassGUI();
        r.setVisible(true);
        close();
    }//GEN-LAST:event_reset_passMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        // TODO add your handling code here:
          ImageIcon i1 = new ImageIcon(getClass().getResource("/labels/login_1.jpg"));
       login.setIcon(i1);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        // TODO add your handling code here:     ImageIcon i1 = new ImageIcon(getClass().getResource("/labels/login_1.jpg"));
               ImageIcon i1 = new ImageIcon(getClass().getResource("/labels/login1.jpg"));
       login.setIcon(i1);
    }//GEN-LAST:event_loginMouseExited

    private void t_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passKeyPressed
        // TODO add your handling code here:
             
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
        
        if(t_user.getText().equals("")||t_pass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the Username and Password .","User Login",2);
        }
        else
        {
                 try {
                     String sql="Select * from accdetails where username=? and password=?";
                     ps=con.prepareStatement(sql);
                     ps.setString(1,t_user.getText() );
                     ps.setString(2,t_pass.getText() );
                     
                     
                     rs=ps.executeQuery();
                     
                     if(rs.next())
                         //  if(t_user.getText().equals(user)&&t_pass.getText().equals(pass))
                     {
                         JOptionPane.showMessageDialog(null,"Login Successful .","User Login",1);
                         
                         MainGUI m = new MainGUI();
                         m.setVisible(true);
                         ps.close();
                         rs.close();
                         close();
                         
                     }
                     else
                     {
                         JOptionPane.showMessageDialog(null,"Invalid Username or Password .","User Login",0);
                         t_user.setText("");
                         t_pass.setText("");
                     }   } catch (SQLException ex) {
                     Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                 }
                       finally{
             try
             {
                 rs.close();
                 ps.close();
             }
             catch(Exception e){}
             
         }
        }
    }     
    
    }//GEN-LAST:event_t_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel login;
    private javax.swing.JLabel reset_pass;
    private javax.swing.JPasswordField t_pass;
    private javax.swing.JTextField t_user;
    // End of variables declaration//GEN-END:variables
}
