/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ezcanteen1;

import java.awt.Color;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows
 */
public class ResetPassGUI extends javax.swing.JFrame {

    /**
     * Creates new form ResetPassGUI
     */
    Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps=null;
    public ResetPassGUI() {
        initComponents();
         this.setSize(691,346);
        this.setLocation(350,150);
        Color c = new Color(40,40,40);
         con=Concls.dbconnect();
        this.getContentPane().setBackground(c);
    }
  public void close()
    {
     WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
     Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        res_pass = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        o_pass = new javax.swing.JPasswordField();
        n_pass = new javax.swing.JPasswordField();
        c_pass = new javax.swing.JPasswordField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(40, 40, 40));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Old Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 150, 151, 32);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 190, 159, 32);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 230, 196, 32);

        res_pass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        res_pass.setForeground(new java.awt.Color(240, 240, 240));
        res_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/reset0.jpg"))); // NOI18N
        res_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        res_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                res_passMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                res_passMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                res_passMouseExited(evt);
            }
        });
        getContentPane().add(res_pass);
        res_pass.setBounds(360, 280, 160, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/min.jpg"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 10, 20, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/close.jpg"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 10, 20, 20);

        back.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(240, 240, 240));
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 300, 90, 30);

        username.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(username);
        username.setBounds(330, 110, 210, 32);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 110, 160, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/labels/reset.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 10, 480, 80);

        o_pass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(o_pass);
        o_pass.setBounds(330, 150, 210, 32);

        n_pass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(n_pass);
        n_pass.setBounds(330, 190, 210, 32);

        c_pass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(c_pass);
        c_pass.setBounds(330, 230, 210, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        username.setText("");
        o_pass.setText("");
        n_pass.setText("");
        c_pass.setText("");
        
        
       
        LoginGUI l = new LoginGUI();
        l.setVisible(true);
        close();
    }//GEN-LAST:event_backMouseClicked

    private void res_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_res_passMouseClicked
        // TODO add your handling code here:
      boolean flag = n_pass.getText().equals(c_pass.getText());
      boolean flag1 = o_pass.getText().equals(n_pass.getText());
     
     
      
      if((o_pass.getText().equals(""))||(n_pass.getText().equals(""))||(c_pass.getText().equals("")))
          JOptionPane.showMessageDialog(null,"Please enter all the fields","EZCanteen",2);
     
      
      
      else if(flag1==true)
          JOptionPane.showMessageDialog(null,"Your old and new passwords should be different","EZCanteen",1);
      
      else if(flag==false)
      {
           JOptionPane.showMessageDialog(null,"New and Confirm passwords do not match","EZCanteen",2);
      
      }
      else
      {
          try {
              //code for setting up the password
              String sql="select * from accdetails Where username=? and password=?";
              
              ps=con.prepareStatement(sql);
              ps.setString(1, username.getText());
              ps.setString(2, o_pass.getText());
              rs=ps.executeQuery();
              if(rs.next())
              {
                  if(n_pass.getText().equals(c_pass.getText()))
                  {
                      int choice = JOptionPane.showConfirmDialog(null,"Are you sure with your new Password ","Reset Password",JOptionPane.YES_NO_OPTION,3, null);
                      String pass =n_pass.getText();
                      String uname=username.getText();
                      String sql1="update accdetails set password='"+pass+"' where username='"+uname+"'";
                      ps=con.prepareStatement(sql1);
                      ps.execute();
                  }
              }
              JOptionPane.showMessageDialog(null,"New Password set successfully","EZCanteen",1);
              o_pass.setText("");
              n_pass.setText("");
              c_pass.setText("");
              
              ps.close();
              rs.close();
              con.close();
              LoginGUI l =new LoginGUI();
              l.setVisible(true);
              close();
          } catch (SQLException ex) {
              Logger.getLogger(ResetPassGUI.class.getName()).log(Level.SEVERE, null, ex);
          }
                finally{
             try
             {
                 rs.close();
                 ps.close();
             }
             catch(Exception e){}
             
         }
      }
          
                
    }//GEN-LAST:event_res_passMouseClicked

    private void res_passMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_res_passMouseEntered
        // TODO add your h  ImageIcon i1 = new ImageIcon(getClass().getResource("/labels/MainMenu1 (1).jpg"));
     
          ImageIcon i1 = new ImageIcon(getClass().getResource("/labels/reset1.jpg"));
        res_pass.setIcon(i1);
    }//GEN-LAST:event_res_passMouseEntered

    private void res_passMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_res_passMouseExited
        // TODO add your handling code here:
         ImageIcon i1 = new ImageIcon(getClass().getResource("/labels/reset0.jpg"));
        res_pass.setIcon(i1);
    }//GEN-LAST:event_res_passMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPassGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPasswordField c_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField n_pass;
    private javax.swing.JPasswordField o_pass;
    private javax.swing.JLabel res_pass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
